config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  # root "projects#index"
  root to: 'projects#index'
  resources :projects

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates_presence_of :title, :description
end

app/models/student.rb
class Student < ApplicationRecord
       # Include default devise modules. Others available are:
       # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
       devise :database_authenticatable, :registerable,
              :recoverable, :rememberable, :validatable
     end

app/models/user.rb
class User < ApplicationRecord
       # Include default devise modules. Others available are:
       # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
       devise :database_authenticatable, :registerable,
              :recoverable, :rememberable, :validatable
     end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  #before_action :authenticate_user!
  
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tyler CS3300 Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <div class="">
    <%= form.text_area :description, :style => "width: 600px; height: 400px;"%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<body style="background-color: #2F4F4F!important;">
<div class="d-flex justify-content-center py-5" style="background-color: #2F4F4F!important;">
<div class="card p-4" style="background-color: #FFC0CB!important;">
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<div class="d-flex justify-content-center">
<%= link_to 'Show', @project, :style => "color: #2F4F4F" %>
<p class="p-1"> | </p>
<%= link_to 'Back', projects_path, :style => "color: #2F4F4F"%>
</div>
</div>
</div>
</body>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<body style="background-color: #2F4F4F!important;">
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #2F4F4F!important;">
  <a class="navbar-brand" href="#" style="color:#FFC0CB!important;">Tyler&apos;s Portfolio</a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link text-white" href="#" style="color:#FFC0CB!important;">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-link" style="color:#FFC0CB!important;">
        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link', :style => 'color:#FFC0CB!important;'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link', :style => 'color:#FFC0CB!important;'   %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link', :style => 'color:#FFC0CB!important;'  %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>


<p id="notice"><%= notice %></p>
<div class="jumbotron">
<div class="container">
  <h1 class="display-3">Tyler Semple Final Project</h1>
  <p>Hello! My name is Tyler Nilsson Semple. I am a junior whom is studying computer science student at University of Colorado Colorado Springs (UCCS).
  This is my portfolio on funny jokes I came across while creating this website in CS3300 or Software Enigneering for short. Welcome, to a place where I try to figure out how CSS and HTML work. Plus for it to not break the code.
  Please add jokes or funny stories using the new project button below. Click the Github Link to look or fork the code. Whatever you please to do. Maybe even click the wierd link :)</p>
  <p><a class="btn btn-primary btn-lg mr-5" href="https://github.com/tsemple90/cs3300" role="button">My GitHub &raquo;</a>
  <a class="btn btn-success btn-lg mr-5" href="https://app.circleci.com/pipelines/github/tsemple90/cs3300" role="button">My CircleCI &raquo;</a>
  <a class="btn btn-danger btn-lg mr-5" href="https://www.youtube.com/watch?v=EoLjddNcnYU" role="button">Click Here :) &raquo;</a>
  <a class="btn btn-warning btn-lg mr-5" href="https://smashthewalls.com/" role="button">USELESS &raquo;</a></p>
</div>
</div>




<h2 class="d-flex justify-content-center" style="color:#FFC0CB!important;">Projects</h1>

<div class="album p-3 row">
<div class="container">
<div class="d-flex row">
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 px-5">
<% @projects.each do |project| %>
    <div class="col-md-4 py-2">
      <div class="card shadow-sm py-3 align-items-center" style="background-color: #FFC0CB!important; min-height: 420px;">
      <div class="d-flex align-items-center">
      <div class="card-body d-flex flex-column align-items-center justify-content-center">
        <h2 class="d-flex justify-content-center text-center"><%= project.title %></h2>
        <div class="col px-2">
          <p class="d-flex justify-content-center text-center lead" style="line-height: 1.75; font-size:14px"><%= project.description %></p>
          <hr>
          <div class="d-flex justify-content-center">
          <p><%= link_to 'Show', project, :style => 'color:#2F4F4F!important;'%></p>
          <% if user_signed_in? %>
            <p class="mx-1">  |  </p>
            <p><%= link_to 'Edit', edit_project_path(project), :style => "color: #2F4F4F" %></p>
            <p class="mx-1">  |  </p>
            <p><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, :style => "color: #2F4F4F" %></p>
          <% end %>
          </div>
        </div>
      </div>
      </div>
      </div>
    </div>
  
<% end %>
</div>
</div>
</div>
</div>


<br>
<div class="px-5 pb-5">
<% if user_signed_in? %>
  <%= link_to 'New Project', new_project_path, :class => 'btn btn-primary', :style => 'color: #FFFFFF!important;'%>
<% end %>
</div>

<footer class="page-footer font-medium">
<a class="btn btn-success btn-lg mr-5" href="https://www.youtube.com/watch?v=U9t-slLl30E" role="button">Secret Tunnel &raquo;</a>
<!-- Copyright -->
<div class="footer-copyright text-center text-primary py-3">© 2021 Copyright:
  <a class="text-warning" href="https://static.wikia.nocookie.net/rise-of-the-brave-tangled-dragons/images/7/71/Lewis.PNG/revision/latest?cb=20150706000459"> TylerSemple.com</a>
</div>
<!-- Copyright -->

</footer>

</body>

app/views/projects/new.html.erb
<body style="background-color: #2F4F4F!important;">
<div class="d-flex justify-content-center py-5" style="background-color: #2F4F4F!important;">
<div class="card p-4" style="background-color: #FFC0CB!important;">
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

</div>
</div>
</body>

app/views/projects/show.html.erb
<body style="background-color: #2F4F4F!important;">
<div class="d-flex justify-content-center p-5" style="background-color: #2F4F4F!important;">
<div class="card p-4" style="background-color: #FFC0CB!important;">
<p id="notice"><%= notice %></p>

<h1>
  <%= @project.title %>
</h1>
<hr>

<p class="text-center lead px-5" style="line-height: 1.75">
  <%= @project.description %>
</p>
<div class="d-flex justify-content-center">
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_project_path(@project), :style => "color: #2F4F4F"  %>
  <p class="p-1">  |  </p>
<% end %>
<%= link_to 'Back', projects_path, :style => "color: #2F4F4F"  %>
</div>
</div>
</div>
</body>